name: Testes Automatizados Mobile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Debug BrowserStack Credentials
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}"
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}"

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Instalar dependências
        run: npm install
      
      - name: Definir credenciais do BrowserStack
        run: |
          echo "BROWSERSTACK_USERNAME=${{ secrets.BROWSERSTACK_USERNAME }}" >> $GITHUB_ENV
          echo "BROWSERSTACK_ACCESS_KEY=${{ secrets.BROWSERSTACK_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Executar testes WebdriverIO
        run: npx wdio wdio.conf.js

      - name: Upload de relatórios Allure (opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
